// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for homepage documents */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismicT.KeyTextField;
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_description: prismicT.KeyTextField;
}
/**
 * Slice for *homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice =
  | CallToActionSlice
  | HeroSlice
  | SponsorsSlice
  | StatisticsSlice
  | TestimonialsSlice
  | TwoColumnContentSlice
  | FooterSlice
  | CopyrightBarSlice;
/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for Menus documents */
interface MenusDocumentData {
  /**
   * Links field in *Menus*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  links: prismicT.GroupField<Simplify<MenusDocumentDataLinksItem>>;
}
/**
 * Item in Menus → Links
 *
 */
export interface MenusDocumentDataLinksItem {
  /**
   * Link Name field in *Menus → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.links[].link_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  link_name: prismicT.RichTextField;
  /**
   * Link field in *Menus → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.links[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
  /**
   * Link Category field in *Menus → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menus.links[].link_category
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link_category: prismicT.KeyTextField;
}
/**
 * Menus document from Prismic
 *
 * - **API ID**: `menus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenusDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<MenusDocumentData>, "menus", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
  /**
   * Logo field in *Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Slice for *Navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = NavigationItemSlice;
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;
export type AllDocumentTypes =
  | HomepageDocument
  | MenusDocument
  | NavigationDocument;
/**
 * Primary content in CallToAction → Primary
 *
 */
interface CallToActionSliceDefaultPrimary {
  /**
   * Headline field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Button label field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismicT.RichTextField;
}
/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CallToActionSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *CallToAction*
 *
 */
type CallToActionSliceVariation = CallToActionSliceDefault;
/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: `CallToAction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CallToActionSlice = prismicT.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;
/**
 * Primary content in CopyrightBar → Primary
 *
 */
interface CopyrightBarSliceDefaultPrimary {
  /**
   * Copyright field in *CopyrightBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_bar.primary.copyright
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  copyright: prismicT.RichTextField;
  /**
   * Symbol field in *CopyrightBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_bar.primary.symbol
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  symbol: prismicT.RichTextField;
  /**
   * Description field in *CopyrightBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_bar.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Item in CopyrightBar → Items
 *
 */
export interface CopyrightBarSliceDefaultItem {
  /**
   * Social Icon field in *CopyrightBar → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_bar.items[].social_icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  social_icon: prismicT.ImageField<never>;
  /**
   * Social Link field in *CopyrightBar → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: copyright_bar.items[].social_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  social_link: prismicT.LinkField;
}
/**
 * Default variation for CopyrightBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CopyrightBarSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<CopyrightBarSliceDefaultPrimary>,
  Simplify<CopyrightBarSliceDefaultItem>
>;
/**
 * Slice variation for *CopyrightBar*
 *
 */
type CopyrightBarSliceVariation = CopyrightBarSliceDefault;
/**
 * CopyrightBar Shared Slice
 *
 * - **API ID**: `copyright_bar`
 * - **Description**: `CopyrightBar`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CopyrightBarSlice = prismicT.SharedSlice<
  "copyright_bar",
  CopyrightBarSliceVariation
>;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
  /**
   * Description field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Headline field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Label field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  label: prismicT.RichTextField;
  /**
   * Button label field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismicT.RichTextField;
  /**
   * Toolbar icon field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.toolbar_icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  toolbar_icon: prismicT.ImageField<never>;
  /**
   * Toolbar label field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.toolbar_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  toolbar_label: prismicT.RichTextField;
  /**
   * Hero image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  hero_image: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in NavigationItem → Primary
 *
 */
interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
  /**
   * Link field in *NavigationItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField;
}
/**
 * Item in NavigationItem → Items
 *
 */
export interface NavigationItemSliceDefaultItem {
  /**
   * Child Name field in *NavigationItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  child_name: prismicT.RichTextField;
  /**
   * Child Link field in *NavigationItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.items[].child_link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  child_link: prismicT.LinkField;
}
/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  Simplify<NavigationItemSliceDefaultItem>
>;
/**
 * Slice variation for *NavigationItem*
 *
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;
/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: `NavigationItem`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationItemSlice = prismicT.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;
/**
 * Item in Sponsors → Items
 *
 */
export interface SponsorsSliceDefaultItem {
  /**
   * Logo field in *Sponsors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.items[].logo
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>;
}
/**
 * Default variation for Sponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SponsorsSliceDefaultItem>
>;
/**
 * Slice variation for *Sponsors*
 *
 */
type SponsorsSliceVariation = SponsorsSliceDefault;
/**
 * Sponsors Shared Slice
 *
 * - **API ID**: `sponsors`
 * - **Description**: `Sponsors`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SponsorsSlice = prismicT.SharedSlice<
  "sponsors",
  SponsorsSliceVariation
>;
/**
 * Item in Statistics → Items
 *
 */
export interface StatisticsSliceDefaultItem {
  /**
   * Number field in *Statistics → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.items[].number
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  number: prismicT.RichTextField;
  /**
   * Description field in *Statistics → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: statistics.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StatisticsSliceDefaultItem>
>;
/**
 * Slice variation for *Statistics*
 *
 */
type StatisticsSliceVariation = StatisticsSliceDefault;
/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: `Statistics`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type StatisticsSlice = prismicT.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;
/**
 * Primary content in Testimonials → Primary
 *
 */
interface TestimonialsSliceDefaultPrimary {
  /**
   * Headline field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *Testimonials → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Item in Testimonials → Items
 *
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Quote field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismicT.RichTextField;
  /**
   * Profile Image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].profile_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  profile_image: prismicT.ImageField<never>;
  /**
   * Name field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
  /**
   * Role field in *Testimonials → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].role
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  role: prismicT.RichTextField;
  /**
   * Quote image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].quote_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  quote_image: prismicT.ImageField<never>;
}
/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;
/**
 * Slice variation for *Testimonials*
 *
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;
/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSlice = prismicT.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;
/**
 * Primary content in TwoColumnContent → Primary
 *
 */
interface TwoColumnContentSliceDefaultPrimary {
  /**
   * Headline field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Button label field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismicT.RichTextField;
}
/**
 * Item in TwoColumnContent → Items
 *
 */
export interface TwoColumnContentSliceDefaultItem {
  /**
   * Icon field in *TwoColumnContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismicT.ImageField<never>;
  /**
   * Headline field in *TwoColumnContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.items[].headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *TwoColumnContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.items[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for TwoColumnContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnContentSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<TwoColumnContentSliceDefaultPrimary>,
  Simplify<TwoColumnContentSliceDefaultItem>
>;
/**
 * Primary content in TwoColumnContent → Primary
 *
 */
interface TwoColumnContentSliceWithButtonsPrimary {
  /**
   * Headline field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Image field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Item in TwoColumnContent → Items
 *
 */
export interface TwoColumnContentSliceWithButtonsItem {
  /**
   * Icon field in *TwoColumnContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismicT.ImageField<never>;
}
/**
 * With buttons variation for TwoColumnContent Slice
 *
 * - **API ID**: `withButtons`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnContentSliceWithButtons = prismicT.SharedSliceVariation<
  "withButtons",
  Simplify<TwoColumnContentSliceWithButtonsPrimary>,
  Simplify<TwoColumnContentSliceWithButtonsItem>
>;
/**
 * Primary content in TwoColumnContent → Primary
 *
 */
interface TwoColumnContentSliceWithButtonNoListPrimary {
  /**
   * Headline field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismicT.RichTextField;
  /**
   * Description field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
  /**
   * Button label field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.button_label
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  button_label: prismicT.RichTextField;
  /**
   * Image field in *TwoColumnContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_content.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * WithButtonNoList variation for TwoColumnContent Slice
 *
 * - **API ID**: `withButtonNoList`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnContentSliceWithButtonNoList =
  prismicT.SharedSliceVariation<
    "withButtonNoList",
    Simplify<TwoColumnContentSliceWithButtonNoListPrimary>,
    never
  >;
/**
 * Slice variation for *TwoColumnContent*
 *
 */
type TwoColumnContentSliceVariation =
  | TwoColumnContentSliceDefault
  | TwoColumnContentSliceWithButtons
  | TwoColumnContentSliceWithButtonNoList;
/**
 * TwoColumnContent Shared Slice
 *
 * - **API ID**: `two_column_content`
 * - **Description**: `TwoColumnContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TwoColumnContentSlice = prismicT.SharedSlice<
  "two_column_content",
  TwoColumnContentSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      HomepageDocument,
      MenusDocumentData,
      MenusDocumentDataLinksItem,
      MenusDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      NavigationDocument,
      AllDocumentTypes,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceDefault,
      CallToActionSliceVariation,
      CallToActionSlice,
      CopyrightBarSliceDefaultPrimary,
      CopyrightBarSliceDefaultItem,
      CopyrightBarSliceDefault,
      CopyrightBarSliceVariation,
      CopyrightBarSlice,
      FooterSliceDefaultPrimary,
      FooterSliceDefault,
      FooterSliceVariation,
      FooterSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceDefaultItem,
      NavigationItemSliceDefault,
      NavigationItemSliceVariation,
      NavigationItemSlice,
      SponsorsSliceDefaultItem,
      SponsorsSliceDefault,
      SponsorsSliceVariation,
      SponsorsSlice,
      StatisticsSliceDefaultItem,
      StatisticsSliceDefault,
      StatisticsSliceVariation,
      StatisticsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceDefault,
      TestimonialsSliceVariation,
      TestimonialsSlice,
      TwoColumnContentSliceDefaultPrimary,
      TwoColumnContentSliceDefaultItem,
      TwoColumnContentSliceDefault,
      TwoColumnContentSliceWithButtonsPrimary,
      TwoColumnContentSliceWithButtonsItem,
      TwoColumnContentSliceWithButtons,
      TwoColumnContentSliceWithButtonNoListPrimary,
      TwoColumnContentSliceWithButtonNoList,
      TwoColumnContentSliceVariation,
      TwoColumnContentSlice,
    };
  }
}
