// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  copyright_bar: dynamic(() => import("./CopyrightBar")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  sponsors: dynamic(() => import("./Sponsors")),
  statistics: dynamic(() => import("./Statistics")),
  testimonials: dynamic(() => import("./Testimonials")),
  two_column_content: dynamic(() => import("./TwoColumnContent")),
};
